import "dotenv/config";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import rateLimit from "express-rate-limit";
import routes from "./routes/index.js";
import { errorHandler, notFound } from "./middleware/errors.js";
const app = express();
const allowedOrigins = (process.env.FRONTEND_URL || "http://localhost:3000").split(",").map((origin) => origin.trim()).filter(Boolean);
app.use(helmet()); app.use(cors({ origin: (origin, callback) => { if (!origin || allowedOrigins.includes(origin)) return callback(null, true); return callback(new Error("Origin is not allowed by CORS")); } })); app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 300 })); app.use(express.json()); app.use(morgan("dev"));
app.get("/health", (_request, response) => response.json({ success: true, message: "HRFlow API is healthy" }));
app.use("/api", routes); app.use(notFound); app.use(errorHandler);
export default app;